### ISSUE TITLE
Deluge 2.0 Compatibility

### ISSUE THREAD

**Issue by Phoenix09** [ratanakvlun/deluge-labelplus#29]
Currently, LabelPlus does not work on Deluge 2.0.

```
04:37:10.089 [DEBUG   ][labelplus.core.core                :116 ] [LabelPlus] Initializing Core...
04:37:10.089 [ERROR   ][deluge.pluginmanagerbase           :183 ] Failed to start plugin: LabelPlus
Traceback: <type 'exceptions.AttributeError'>: 'TorrentManager' object has no attribute 'session_started'
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:150:maybeDeferred
/usr/lib/python2.7/dist-packages/deluge/plugins/init.py:27:enable
/home/administrator/.config/deluge/plugins/LabelPlus-0.3.2.2-py2.7.egg/labelplus/core/core.py:118:enable

04:37:10.089 [DEBUG   ][labelplus.core.core                :336 ] [LabelPlus] Deinitializing Core...
04:37:10.090 [DEBUG   ][deluge.pluginmanagerbase           :218 ] Error when disabling plugin LabelPlus: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/deluge/pluginmanagerbase.py", line 185, in on_started_error
    self.disable_plugin(plugin_name)
  File "/usr/lib/python2.7/dist-packages/deluge/core/pluginmanager.py", line 73, in disable_plugin
    d = deluge.pluginmanagerbase.PluginManagerBase.disable_plugin(self, name)
  File "/usr/lib/python2.7/dist-packages/deluge/pluginmanagerbase.py", line 209, in disable_plugin
    d = defer.maybeDeferred(self.plugins[name].disable)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/deluge/plugins/init.py", line 30, in disable
    return self.plugin.disable()
  File "/home/administrator/.config/deluge/plugins/LabelPlus-0.3.2.2-py2.7.egg/labelplus/core/core.py", line 350, in disable
    
exceptions.AttributeError: 'Core' object has no attribute '_orig_set_torrent'

04:37:10.090 [DEBUG   ][deluge.component                   :286 ] Deregistering Component: CorePlugin.LabelPlus
04:37:10.090 [INFO    ][deluge.pluginmanagerbase           :229 ] Plugin LabelPlus disabled...
```

**Comment by ratanakvlun** [comment]
I am not currently working on a Deluge 2.0 version until there is a stable release. This is mainly because I don't want to get caught up with breaking changes all over the place.
